print("Hello world!")
print("zor günler geride kaldı!")
print("naber lan!")
print("En büyük takım BEŞİKTAŞ")
print("güzel günler çok yakındır.")
print("algoritma yazılım kodlama")
print("SELAMÜNALEYKÜM")
print("izmirli ismail")
print("ahmet'ler")
#açıklama satırları # karekterleri ile başlar
print("Hayırlı Cumalar...")
print("NABER TREK")
print("Hayırdır lan")
print("Ya Allah")